# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unique_sort_native <- function(x) {
    .Call('_selectiveModel_unique_sort_native', PACKAGE = 'selectiveModel', x)
}

construct_midpoints <- function(x) {
    .Call('_selectiveModel_construct_midpoints', PACKAGE = 'selectiveModel', x)
}

which_native <- function(x) {
    .Call('_selectiveModel_which_native', PACKAGE = 'selectiveModel', x)
}

consecutive_true <- function(vec) {
    .Call('_selectiveModel_consecutive_true', PACKAGE = 'selectiveModel', vec)
}

unlist_native <- function(list) {
    .Call('_selectiveModel_unlist_native', PACKAGE = 'selectiveModel', list)
}

theta_in_matrix <- function(x, mat) {
    .Call('_selectiveModel_theta_in_matrix', PACKAGE = 'selectiveModel', x, mat)
}

theta_in_all_matrix <- function(x, list) {
    .Call('_selectiveModel_theta_in_all_matrix', PACKAGE = 'selectiveModel', x, list)
}

intersect_intervals <- function(list) {
    .Call('_selectiveModel_intersect_intervals', PACKAGE = 'selectiveModel', list)
}

rcpp_hello_world <- function() {
    .Call('_selectiveModel_rcpp_hello_world', PACKAGE = 'selectiveModel')
}

test <- function() {
    .Call('_selectiveModel_test', PACKAGE = 'selectiveModel')
}

func1 <- function(x, list) {
    .Call('_selectiveModel_func1', PACKAGE = 'selectiveModel', x, list)
}

func2 <- function() {
    .Call('_selectiveModel_func2', PACKAGE = 'selectiveModel')
}

