# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unique_sort_native <- function(x) {
    .Call('_selectiveModel_unique_sort_native', PACKAGE = 'selectiveModel', x)
}

construct_midpoints <- function(x) {
    .Call('_selectiveModel_construct_midpoints', PACKAGE = 'selectiveModel', x)
}

theta_in_matrix <- function(x, mat) {
    .Call('_selectiveModel_theta_in_matrix', PACKAGE = 'selectiveModel', x, mat)
}

rcpp_hello_world <- function() {
    .Call('_selectiveModel_rcpp_hello_world', PACKAGE = 'selectiveModel')
}

test <- function() {
    .Call('_selectiveModel_test', PACKAGE = 'selectiveModel')
}

